DROP TABLE IF EXISTS TB_BRINFO;
 
CREATE TABLE TB_BRINFO(	
BR_CODE	  VARCHAR(3) ,
BR_NM  VARCHAR(10)
);	

DROP TABLE IF EXISTS TB_ACCTINFO;

CREATE TABLE TB_ACCTINFO(	
ACCT_NO  VARCHAR(8)  ,
ACCT_NM  VARCHAR(20),
BR_CODE   VARCHAR(3)
);	

DROP TABLE IF EXISTS TB_DEDTLS;

CREATE TABLE TB_DEDTLS(	
DE_DM	 VARCHAR(8) ,
ACCT_NO	 VARCHAR(8) ,
DE_NO	 VARCHAR(25),
AMT	 INT,
FEE	 INT,
CAN_AT	 VARCHAR(1)
);	
